# Environment
env:
  env_id: "CartPole-v1"
  max_episode_steps: 500
  action_space_type: "discrete"
  state_space_type: "continuous"

# Network Architecture
network:
  actor_hidden_sizes: [64, 64]
  critic_hidden_sizes: [64, 64]
  activation: "tanh"
  layer_norm: false

# Training Process
training:
  total_timesteps: 100000
  batch_size: 64
  learning_rate: 0.0003
  device: "cuda"
  seed: 42
  num_envs: 8
  eval_freq: 5000

# PPO Specific
algorithm:
  n_steps: 2048
  n_epochs: 10
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.0
  vf_coef: 0.5
  max_grad_norm: 0.5

# Logging
logging:
  log_dir: "logs/ppo_cartpole"
  tensorboard: true
  verbose: 1